# .github/release.yml

changelog:
  exclude:
    labels:
      - '^build:'
      - '^ci:'
  categories:
    - title: '🚀 Features'
      labels:
        - 'feature'
    - title: '🐛 Bug Fixes'
      labels:
        - 'fix'
    - title: '🔨 Improvements'
      labels:
        - 'improvement'
    - title: '🧪 Tests'
      labels:
        - 'test'
    - title: '🔨 Refactor'
      labels:
        - 'refactor'
    - title: '📝 Documentation'
      labels:
        - 'docs'
    - title: '🔧 Maintenance'
      labels:
        - 'chore'
        - 'build'
        - 'ci'
