name: Generate Semantic Release
on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout Entire Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Setup dependencies
        run: |
          npm install @semantic-release/git @semantic-release/exec --no-save

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: "DAS DevOps"
          GIT_AUTHOR_EMAIL: "devops@dhiashalabi.dev"
          GIT_COMMITTER_NAME: "DAS DevOps"
          GIT_COMMITTER_EMAIL: "devops@dhiashalabi.dev"
        run: npx semantic-release
